/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#include <Foundation/Foundation.h>

@class XMLTree;

@interface APIResponse : NSObject
{
    int apiType;
    XMLTree *xmlResponse;
    NSError *networkError;
    int httpStatusCode;
    NSString *shortErrorMessage;
    NSString *longErrorMessage;
    double elapsedTime;
}

+ (id)response;
- (void)parseData:(id)fp8;
- (void)setupFromResponse;
- (id)stringValue;
- (id)description;
- (void)dealloc;
- (id)errorCodeDescription;
- (BOOL)success;
- (BOOL)recoverableAPIError;
- (BOOL)reportableAPIError;
- (id)longErrorMessage;
- (void)setLongErrorMessage:(id)fp8;
- (id)shortErrorMessage;
- (void)setShortErrorMessage:(id)fp8;
- (int)apiType;
- (void)setApiType:(int)fp8;
- (id)xmlResponse;
- (void)setXmlResponse:(id)fp8;
- (id)networkError;
- (void)setNetworkError:(id)fp8;
- (int)httpStatusCode;
- (void)setHttpStatusCode:(int)fp8;
- (double)elapsedTime;
- (void)setElapsedTime:(double)fp8;

@end

