/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#include <Foundation/Foundation.h>

@class XMLNode, XMLTree;

@interface APIRequest
{
    int apiType;
    int activityType;
    XMLTree *tree;
    XMLNode *rootNode;
    BOOL hasBeenBuilt;
    BOOL retryOnRecoverableError;
    BOOL doNotReportAPIErrors;
    int totalBytesToTransmit;
    Class responseClass;
    NSObject *progressDelegate;
}

- (id)data;
- (id)stringValue;
- (id)description;
- (void)buildRequest;
- (id)apiURL;
- (void)dealloc;
- (id)buildResponse;
- (id)shortDebugDescription;
- (id)progressDelegate;
- (void)setProgressDelegate:(id)fp8;
- (int)apiType;
- (void)setApiType:(int)fp8;
- (Class)responseClass;
- (void)setResponseClass:(Class)fp8;
- (id)rootNode;
- (void)setRootNode:(id)fp8;
- (BOOL)retryOnRecoverableError;
- (void)setRetryOnRecoverableError:(BOOL)fp8;
- (int)totalBytesToTransmit;
- (void)setTotalBytesToTransmit:(int)fp8;
- (int)activityType;
- (void)setActivityType:(int)fp8;
- (BOOL)doNotReportAPIErrors;
- (void)setDoNotReportAPIErrors:(BOOL)fp8;

@end

