/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface CurrencyAmount :  NSObject
{
    NSDecimalNumber *amount;
    NSString *currencyID;
}

+ (void)load;
+ (BOOL)isCurrencyNodeName:(id)fp8;
+ (id)zeroAmount;
+ (id)zeroAmountWithCurrencyID:(id)fp8;
+ (id)amountWithDoubleAmount:(double)fp8;
+ (id)amountWithStringAmount:(id)fp8;
+ (id)stringByRemovingThousandsSeparatorsFromString:(id)fp8 withLocale:(id)fp12;
+ (id)defaultCurrencyID;
+ (id)currencyPrefixShort:(BOOL)fp8 forCurrencyID:(id)fp12;
+ (id)numberFormatterForCurrencyID:(id)fp8;
- (id)minimumListingFixedPriceAmount;
- (id)initWithNode:(id)fp8;
- (id)initWithDoubleAmount:(double)fp8 currencyID:(id)fp16;
- (id)initWithStringAmount:(id)fp8 currencyID:(id)fp12;
- (id)initWithStringAmount:(id)fp8 currencyID:(id)fp12 locale:(id)fp16;
- (id)initWithLocalizedStringAmount:(id)fp8 currencyID:(id)fp12;
- (id)initWithDecimalAmount:(id)fp8 currencyID:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)currencyAmountByDividingByQuantity:(int)fp8;
- (id)currencyAmountByMultiplyingByQuantity:(int)fp8;
- (id)currencyAmountByAdding:(id)fp8;
- (id)currencyAmountBySubtracting:(id)fp8;
- (id)currencyAmountByRoundingToNearestPenny;
- (id)stringValue;
- (id)rawDecimalAsString;
- (id)currencyPrefixShort:(BOOL)fp8;
- (id)formatStringWithoutCurrency;
- (id)formatStringForAPI;
- (id)formatStringIntegral;
- (id)formatStringTruncate;
- (id)formatStringShort:(BOOL)fp8;
- (id)description;
- (BOOL)canCompare:(id)fp8;
- (int)compare:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (BOOL)isZeroAmount;
- (void)dealloc;
- (id)currencyID;
- (void)setCurrencyID:(id)fp8;
- (id)amount;
- (void)setAmount:(id)fp8;

@end

