/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */


#import <Foundation/Foundation.h>

@class UIImage;


@interface EbaySite : NSObject
{
    NSNumber *siteID;
    NSString *isoCode;
    NSString *countryName;
    NSString *globalID;
    NSString *recommendationServiceSiteSpecifier;
    NSString *logoFileName;
    UIImage *logo;
    NSString *flagFileName;
    UIImage *flag;
    NSString *currencyID;
    NSString *registrationSite;
    NSString *payPalURL;
    NSString *motorsCategoryID;
    BOOL searchExcludeStoreInventory;
    NSString *searchItemLocationRegion;
    NSString *searchPreferredLocation;
    BOOL metricUnits;
    BOOL allowBestOfferTerms;
    BOOL allowBestOffer;
    NSString *intlCallingCode;
    NSString *searchSuggestionVersionDCSPropName;
    NSString *searchSuggestionVersionURL;
    NSString *searchSuggestionBaseURL;
    NSString *dealOfTheDayAPI;
    NSString *dealsFileName;
    NSString *defaultDealsFileName;
    NSArray *popularCategoryIDs;
    NSArray *popularCategoryIDsToExclude;
    NSArray *hiddenAppBundleIDs;
    int postCodeLength;
    NSString *siteSuffix;
    BOOL usesComplexReturnPolicies;
}

+ (id)siteListFromPList:(id)fp8;
+ (id)siteListFromPListPath:(id)fp8;
+ (id)siteFromList:(id)fp8 forLocale:(id)fp12;
+ (id)siteFromList:(id)fp8 withSiteId:(id)fp12;
+ (id)siteLocalizeString:(id)fp8;
+ (id)siteLocalizedContentsOfResourceNamed:(id)fp8 ofType:(id)fp12;
- (void)dealloc;
- (id)categoryIDsFromCommentedList:(id)fp8;
- (id)initFromDict:(id)fp8;
- (void)lowMemoryWarning:(id)fp8;
- (id)logo;
- (id)flag;
- (id)languageAndISOCode;
- (id)siteLocalizeString:(id)fp8;
- (id)UTF8StringWithContentsOfResource:(id)fp8 ofType:(id)fp12;
- (id)siteLocalizedContentsOfResourceNamed:(id)fp8 ofType:(id)fp12;
- (id)siteSuffix;
- (void)setSiteSuffix:(id)fp8;
- (int)postCodeLength;
- (void)setPostCodeLength:(int)fp8;
- (id)hiddenAppBundleIDs;
- (void)setHiddenAppBundleIDs:(id)fp8;
- (id)defaultDealsFileName;
- (void)setDefaultDealsFileName:(id)fp8;
- (id)dealsFileName;
- (void)setDealsFileName:(id)fp8;
- (id)dealOfTheDayAPI;
- (void)setDealOfTheDayAPI:(id)fp8;
- (id)searchSuggestionBaseURL;
- (void)setSearchSuggestionBaseURL:(id)fp8;
- (id)searchSuggestionVersionURL;
- (void)setSearchSuggestionVersionURL:(id)fp8;
- (id)intlCallingCode;
- (void)setIntlCallingCode:(id)fp8;
- (id)motorsCategoryID;
- (void)setMotorsCategoryID:(id)fp8;
- (id)payPalURL;
- (void)setPayPalURL:(id)fp8;
- (BOOL)allowBestOffer;
- (void)setAllowBestOffer:(BOOL)fp8;
- (BOOL)allowBestOfferTerms;
- (void)setAllowBestOfferTerms:(BOOL)fp8;
- (BOOL)metricUnits;
- (void)setMetricUnits:(BOOL)fp8;
- (id)registrationSite;
- (void)setRegistrationSite:(id)fp8;
- (id)currencyID;
- (void)setCurrencyID:(id)fp8;
- (id)flagFileName;
- (void)setFlagFileName:(id)fp8;
- (id)logoFileName;
- (void)setLogoFileName:(id)fp8;
- (id)countryName;
- (void)setCountryName:(id)fp8;
- (id)isoCode;
- (void)setIsoCode:(id)fp8;
- (id)siteID;
- (void)setSiteID:(id)fp8;
- (id)globalID;
- (void)setGlobalID:(id)fp8;
- (BOOL)searchExcludeStoreInventory;
- (void)setSearchExcludeStoreInventory:(BOOL)fp8;
- (id)searchItemLocationRegion;
- (void)setSearchItemLocationRegion:(id)fp8;
- (id)searchPreferredLocation;
- (void)setSearchPreferredLocation:(id)fp8;
- (id)recommendationServiceSiteSpecifier;
- (void)setRecommendationServiceSiteSpecifier:(id)fp8;
- (BOOL)usesComplexReturnPolicies;
- (void)setUsesComplexReturnPolicies:(BOOL)fp8;
- (id)popularCategoryIDs;
- (void)setPopularCategoryIDs:(id)fp8;
- (id)popularCategoryIDsToExclude;
- (void)setPopularCategoryIDsToExclude:(id)fp8;
- (id)searchSuggestionVersionDCSPropName;
- (void)setSearchSuggestionVersionDCSPropName:(id)fp8;

@end

