/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "APIResponse.h"
#include <Foundation/Foundation.h>

@interface EBaySOAResponse : APIResponse
{
    NSString *ack;
    NSString *errorId;
    NSString *errorDomain;
    NSString *errorSubdomain;
    NSString *errorSeverity;
    NSString *errorCategory;
    NSString *errorParameter;
}

- (void)dealloc;
- (void)setupFromResponse;
- (void)fetchErrorsFromNode:(id)fp8;
- (id)errorCodeDescription;
- (BOOL)success;
- (id)ack;
- (void)setAck:(id)fp8;
- (id)errorCategory;
- (void)setErrorCategory:(id)fp8;
- (id)errorSeverity;
- (void)setErrorSeverity:(id)fp8;
- (id)errorSubdomain;
- (void)setErrorSubdomain:(id)fp8;
- (id)errorDomain;
- (void)setErrorDomain:(id)fp8;
- (id)errorId;
- (void)setErrorId:(id)fp8;
- (id)errorParameter;
- (void)setErrorParameter:(id)fp8;

@end

