/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */
#import <Foundation/Foundation.h>
#import "APIRequest.h"

@interface EBayConnector :  NSObject
{
    BOOL requestLoadFailed;
    APIRequest *request;
    NSMutableData *data;
    NSMutableDictionary *context;
    NSError *networkError;
    NSDictionary *responseHeaders;
    NSString *contentType;
    int httpStatusCode;
    NSURLConnection *apiConnection;
    id eBayApiDelegate;
    int truncateLoggingLength;
    int totalBytesTransmitted;
    id target;
    SEL action;
}

+ (id)sendAsyncRequest:(id)fp8 delegate:(id)fp12;
+ (void)sendRequestOnThread:(id)fp8 returningToTarget:(id)fp12 action:(SEL)fp16;
+ (id)sendRequest:(id)fp8;
+ (id)connectorWithRequest:(id)fp8;
+ (void)updateTotalBytes:(int)fp8 time:(double)fp12;
+ (double)averageBytesPerSecond;
- (id)initRequest:(id)fp8;
- (void)dealloc;
- (id)sendRequest;
- (id)getResponse;
- (void)sendAsyncRequest;
- (BOOL)shouldLogXML;
- (BOOL)shouldHideBackgroundActivity;
- (void)updateProgress:(float)fp8 forConnection:(id)fp12;
- (id)sendRequestReturningData;
- (void)cancelConnection;
- (id)setupRequest;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (SEL)action;
- (void)setAction:(SEL)fp8;
- (id)target;
- (void)setTarget:(id)fp8;
- (id)eBayApiDelegate;
- (void)setEBayApiDelegate:(id)fp8;
- (id)apiConnection;
- (void)setApiConnection:(id)fp8;
- (id)request;
- (void)setRequest:(id)fp8;
- (id)contentType;
- (void)setContentType:(id)fp8;
- (id)responseHeaders;
- (void)setResponseHeaders:(id)fp8;

@end

