/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#include "EBaySOAResponse.h"

@class NSArray, NSDictionary, NSMutableArray;

@interface FSFindItemsAdvancedResponse : EBaySOAResponse
{
    NSDictionary *findItemsDict;
    NSMutableArray *items;
    NSArray *categoryHistogram;
    NSDictionary *aspectHistogram;
}

- (void)setupFromResponse;
- (void)setupFromNode:(id)fp8;
- (void)dealloc;
- (BOOL)processNode:(id)fp8 intoDictionary:(id)fp12;
- (BOOL)shouldContainNodeSiblingsInArray:(id)fp8;
- (BOOL)shouldContainNodeChildrenInArray:(id)fp8;
- (int)totalNumberOfPages;
- (int)totalNumberOfItems;
- (id)categoryHistogram;
- (BOOL)categoryHistogramIsEmpty;
- (id)aspectHistogram;
- (BOOL)aspectHistogramIsEmpty;
- (id)items;
- (void)setItems:(id)fp8;

@end

