/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

// #import "EBaySOARequest.h"
#import "CurrencyAmount.h"

@class CurrencyAmount;

@interface FSFindItemsAdvancedRequest : NSObject // EBaySOARequest
{
    NSString *query;
    int pageNumber;
    int maxEntries;
    int maxDistance;
    NSString *itemSort;
    NSString *includeSelector;
    BOOL excludeAutoPay;
    BOOL hideDuplicates;
    NSMutableArray *itemTypeArray;
    NSString *categoryID;
    BOOL searchWorldwide;
    BOOL searchOtherCountries;
    BOOL searchDescriptions;
    CurrencyAmount *priceMin;
    CurrencyAmount *priceMax;
    NSString *sellerID;
    NSString *fullquery;
    NSString *postalCode;
    BOOL bestOfferRequired;
    float maxHoursLeft;
    NSString *itemCondition;
    int minBids;
    int maxBids;
    BOOL _ignoreBidCount;
    NSMutableArray *aspectFilterArray;
    BOOL includeAspectHistogram;
    BOOL includeCategoryHistogram;
}

+ (id)requestWithQuery:(id)fp8;
+ (id)requestWithSellerID:(id)fp8;
- (id)apiURL;
- (id)siteIDOverride;
- (void)addItemType:(id)fp8;
- (id)init;
- (id)fullquery;
- (void)setupDefaults;
- (id)initWithQuery:(id)fp8;
- (id)initWithSellerID:(id)fp8;
- (void)dealloc;
- (id)itemFilterName:(id)fp8 value:(id)fp12;
- (id)itemFilterName:(id)fp8 boolValue:(BOOL)fp12;
- (id)itemFilterName:(id)fp8 intValue:(int)fp12;
- (id)itemFilterName:(id)fp8 values:(id)fp12;
- (void)buildRequest;
- (void)parameterizeFromSearchOptionsContainer:(id)fp8;
- (void)addAspectFilterName:(id)fp8 values:(id)fp12;
- (void)validateDistanceSearch;
- (void)validateItemTypes;
- (BOOL)_ignoreBidCount;
- (void)set_ignoreBidCount:(BOOL)fp8;
- (int)maxBids;
- (void)setMaxBids:(int)fp8;
- (int)minBids;
- (void)setMinBids:(int)fp8;
- (id)itemCondition;
- (void)setItemCondition:(id)fp8;
- (float)maxHoursLeft;
- (void)setMaxHoursLeft:(float)fp8;
- (BOOL)bestOfferRequired;
- (void)setBestOfferRequired:(BOOL)fp8;
- (id)postalCode;
- (void)setPostalCode:(id)fp8;
- (id)sellerID;
- (void)setSellerID:(id)fp8;
- (id)priceMax;
- (void)setPriceMax:(id)fp8;
- (id)priceMin;
- (void)setPriceMin:(id)fp8;
- (int)maxDistance;
- (void)setMaxDistance:(int)fp8;
- (BOOL)searchOtherCountries;
- (void)setSearchOtherCountries:(BOOL)fp8;
- (id)categoryID;
- (void)setCategoryID:(id)fp8;
- (id)includeSelector;
- (void)setIncludeSelector:(id)fp8;
- (id)itemSort;
- (void)setItemSort:(id)fp8;
- (BOOL)hideDuplicates;
- (void)setHideDuplicates:(BOOL)fp8;
- (BOOL)excludeAutoPay;
- (void)setExcludeAutoPay:(BOOL)fp8;
- (int)maxEntries;
- (void)setMaxEntries:(int)fp8;
- (int)pageNumber;
- (void)setPageNumber:(int)fp8;
- (id)query;
- (void)setQuery:(id)fp8;
- (void)setFullquery:(id)fp8;
- (BOOL)searchDescriptions;
- (void)setSearchDescriptions:(BOOL)fp8;
- (BOOL)searchWorldwide;
- (void)setSearchWorldwide:(BOOL)fp8;
- (BOOL)includeCategoryHistogram;
- (void)setIncludeCategoryHistogram:(BOOL)fp8;
- (BOOL)includeAspectHistogram;
- (void)setIncludeAspectHistogram:(BOOL)fp8;

@end

